#!/bin/bash

pwd

mkdir DB 2>/dev/null
  
PS3="Select a choice: "
  select dbselector in "Create Database" "List Database" "Connect Database" "Drop Database" "exit"
do  
   case $REPLY in
    1) bash ./dbfunc/dbcr ; break;;
    2) bash ./dbfunc/dbls ; break;;
    3) bash ./dbfunc/dbcnn ; break;;
    4) bash ./dbfunc/dbdrp ; break;;
    5) exit ;;
    *) echo -e "\n\t\tWrong! \n\ttry again\n" ; bash main ;;
  esac
done