#!/bin/bash
  read -p "Enter Table Name: " tabname
  read -p "Enter y to remove $tabname :" inp
  if [[ "y" == "$inp" ]]; then
  rm -r $tabname .$tabname.meta 2>/dev/null
  fi
  if [[ $? == 0 ]]; then
    echo "Table Dropped Successfully"
  else
    echo "Error Dropping Table $tabname"
  fi