#!/bin/bash

select col in "Select All Columns of a Table" "Select Specific Column from a Table" "Select From Table under condition" "Back To Tables Menu" "Back To Main Menu" "Exit"
do
  case $REPLY in
    1)  read -p "Enter Table Name: " tabname
        column -t -s ':' $tabname 2>/dev/null
        if [[ $? != 0 ]]; then
        echo "Error Displaying Table $tabname"
        fi;;
    2)  read -p "Enter Table Name: " tabname 
        read -p "Enter Column Number: " colNum
        awk 'BEGIN{FS=":"}{print $'$colNum'}' $tabname ;;
    3) clear; selectCon ;;
    4) clear; tablesMenu ;;
    5) clear; cd ../.. 2>/dev/null; mainMenu ;;
    6) exit ;;
    *) echo "\n\t\tWrong! \n\ttry again\n" ; selectMenu;
  esac
done