#!/bin/bash
  read -p "Enter Database Name: " dbname
  if [ -z $dbname ] 
  then 
    echo "It is empty input. Please enter Name..."
  else
  mkdir ./DB/$dbname 2>> /dev/null
  if [[ $? == 0 ]]
  then
    echo "Database Created Successfully"
    bash main
  else
    echo "Error Creating Database $dbname"
    bash main
  fi
  fi
