#!/bin/bash
  read -p "Enter Database Name: " dbname
  if [ -z $dbname ] 
     then 
    echo "It is empty input. Please enter Name..."

  elif [ -d ./DB/$dbname ]
        then
            echo "This Database is already exist"
  else
            mkdir ./DB/$dbname
            echo "Database created successfully!"
        
  fi
  bash main
