#!/bin/bash
  read -p "Enter Database Name: " dbname
  rm -r ./DB/$dbname 2>/dev/null
  if [[ $? == 0 ]]; then
    echo "Database Dropped Successfully"
  else
    echo "Database Not found"
  fi
bash main
