#!/bin/bash
  read -p "Enter Database Name: " dbname
  
  if [ -d ./DB/$dbname ]
	then
	      rm -r ./DB/$dbname 2> /dev/null
        echo "Database $dbname Dropped Successfully"
  else
        echo "Database Not found"
  fi
bash main
